//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Orders.WebApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Orders.WebApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Categories (CategoryID INTEGER PRIMARY KEY, CategoryName TEXT, Description TEXT);
        ///CREATE TABLE Suppliers (SupplierID INTEGER PRIMARY KEY, CompanyName TEXT, ContactName TEXT, ContactTitle TEXT, Address TEXT, City TEXT, Region TEXT, PostalCode TEXT, Country TEXT, Phone TEXT, Fax TEXT, HomePage TEXT);
        ///CREATE TABLE Products (ProductID INTEGER PRIMARY KEY, ProductName TEXT, SupplierID INTEGER, CategoryID INTEGER, QuantityPerUnit TEXT, UnitPrice REAL, UnitsInStock INTEGER, UnitsOnOrder INTEGER, Reo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTables {
            get {
                return ResourceManager.GetString("CreateTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Orders VALUES (10248,&apos;VINET&apos;,5,&apos;7/4/1996&apos;,&apos;8/1/1996&apos;,&apos;7/16/1996&apos;,3,32.38,&apos;Vins et alcools Chevalier&apos;,&apos;59 rue de l&apos;&apos;Abbaye&apos;,&apos;Reims&apos;,NULL,&apos;51100&apos;,&apos;France&apos;)
        ///INSERT INTO Orders VALUES (10249,&apos;TOMSP&apos;,6,&apos;7/5/1996&apos;,&apos;8/16/1996&apos;,&apos;7/10/1996&apos;,1,11.61,&apos;Toms Spezialitäten&apos;,&apos;Luisenstr. 48&apos;,&apos;Münster&apos;,NULL,&apos;44087&apos;,&apos;Germany&apos;)
        ///INSERT INTO Orders VALUES (10250,&apos;HANAR&apos;,4,&apos;7/8/1996&apos;,&apos;8/5/1996&apos;,&apos;7/12/1996&apos;,2,65.83,&apos;Hanari Carnes&apos;,&apos;Rua do Paço, 67&apos;,&apos;Rio de Janeiro&apos;,&apos;RJ&apos;,&apos;05454-876&apos;,&apos;Brazil&apos;)
        ///INSERT INTO Orders VALU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitializeOrders {
            get {
                return ResourceManager.GetString("InitializeOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Categories VALUES (1,&apos;Beverages&apos;,&apos;Soft drinks, coffees, teas, beers, and ales&apos;);
        ///INSERT INTO Categories VALUES (2,&apos;Condiments&apos;,&apos;Sweet and savory sauces, relishes, spreads, and seasonings&apos;);
        ///INSERT INTO Categories VALUES (3,&apos;Confections&apos;,&apos;Desserts, candies, and sweet breads&apos;);
        ///INSERT INTO Categories VALUES (4,&apos;Dairy Products&apos;,&apos;Cheeses&apos;);
        ///INSERT INTO Categories VALUES (5,&apos;Grains/Cereals&apos;,&apos;Breads, crackers, pasta, and cereal&apos;);
        ///INSERT INTO Categories VALUES (6,&apos;Meat/Poultry&apos;,&apos;Prepared meats&apos;); [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitializeTables {
            get {
                return ResourceManager.GetString("InitializeTables", resourceCulture);
            }
        }
    }
}
